graphhopper:
  datareader.file: /graphhopper/data/ural-fed-district-260412.osm.pbf
  graph.location: /graphhopper/data/russia-cache
  import.osm.ignored_highways: ""

  prepare.min_network_size: 200
  prepare.min_one_way_network_size: 200
  
  prepare.lm.threads: 2
  prepare.lm.min_network_size: 200

  graph.encoded_values: car_access, car_average_speed, country, road_class, roundabout, max_speed, foot_access, foot_average_speed, foot_priority, foot_road_access, hike_rating, bike_access, bike_average_speed, bike_priority, bike_road_access, bike_network, mtb_rating, ferry_speed, road_environment
  profiles:
    - name: car
      custom_model_files: [car.json]
    # - name: bike
    #   custom_model_files: [bike.json]
    # - name: foot
    #   custom_model_files: [foot.json]
    - name: car_only
      custom_model: {
          "speed": [
              { "if": "true", "limit_to": "car_average_speed" }
          ],
          "priority": [
              {
                "if": "road_class == PATH || road_class == PEDESTRIAN || road_class == STEPS || road_class == BRIDLEWAY || road_class == TRACK",
                "multiply_by": "0.0"
              }
          ]
        }
  profiles_ch:
    - profile: car
    - profile: car_only
  # profiles_lm:
  #   - profile: car
server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 0.0.0.0