services:
  webappcellmapper:
    image: ${DOCKER_REGISTRY-}webappcellmapper
    build:
      context: .
      dockerfile: WebAppCellMapper/Dockerfile # WebAppCellMapper/ для vs2022 Dockerfile
    env_file:
      - ./environment
    depends_on:
      - db_postgres17
   # restart: on-failure   Перезапускать при ошибке

  webapplocator:
    image: ${DOCKER_REGISTRY-}webapplocator
    build:
      context: .
      dockerfile: WebAppLocator/Dockerfile
    env_file:
      - ./environment
    depends_on:
      - db_postgres17

  db_postgres17:
    image: postgres:17-alpine
    container_name: postgres17
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: ConfigManager
    ports:
        - "54321:5432"
    volumes:
        - db_postgres17:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "5050:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin 

 # не много улучшает точность
  # graphhopper:
  #   image: israelhikingmap/graphhopper:latest 
  #   container_name: graphhopper
  #   ports:
  #     - "8989:8989"
  #     - "8990:8990"
  #   volumes:
  #     - ./data:/graphhopper/data
  #     - ./config.yml:/graphhopper/config/config.yml
  #   environment:
  #     - JAVA_OPTS=-Xms2g -Xmx2g
  #   command:
  #     - --config
  #     - /graphhopper/config/config.yml
  #     - --host
  #     - 0.0.0.0
 
volumes:
  db_postgres17:
  pgadmin4:  
  webappcellmapper:
  #graphhopper:

  




