services:
  webappcellmapper:
    image: ${DOCKER_REGISTRY-}webappcellmapper
    build:
      context: .
      dockerfile: WebAppCellMapper/Dockerfile # для vs2022 Dockerfile
    environment:
      - PG_HOST=db_postgres17
      - PG_PORT=5432
      - PG_DATABASE=ConfigManager
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_SERVER=db_postgres17:5432
    depends_on:
      - db_postgres17
   # restart: on-failure   Перезапускать при ошибке


  db_postgres17:
    image: postgres:17-alpine
    container_name: postgres17
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: ConfigManager
    ports:
        - "54321:5432"
    volumes:
        - db_postgres17:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "5050:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin 
volumes:
  db_postgres17:
  pgadmin4:  
  webappcellmapper:


  



