// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAppCellMapper.Data;

#nullable disable

namespace WebAppCellMapper.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260328063038_AddProgress")]
    partial class AddProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAppCellMapper.Data.Models.Operator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VisibleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("operators");
                });

            modelBuilder.Entity("WebAppCellMapper.Data.Models.OperatorProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AddedStationsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    b.Property<int>("ScannedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("progresses");
                });

            modelBuilder.Entity("WebAppCellMapper.Data.Models.Station", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bands")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BsType")
                        .HasColumnType("integer");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<int>("LocType")
                        .HasColumnType("integer");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<int>("Num")
                        .HasColumnType("integer");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("stations");
                });

            modelBuilder.Entity("WebAppCellMapper.Data.Models.OperatorProgress", b =>
                {
                    b.HasOne("WebAppCellMapper.Data.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("WebAppCellMapper.Services.SquareSearch", "Coordinates", b1 =>
                        {
                            b1.Property<long>("OperatorProgressId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<bool>("IsScanned")
                                .HasColumnType("boolean");

                            b1.Property<double>("LatEnd")
                                .HasColumnType("double precision");

                            b1.Property<double>("LatStart")
                                .HasColumnType("double precision");

                            b1.Property<double>("LonEnd")
                                .HasColumnType("double precision");

                            b1.Property<double>("LonStart")
                                .HasColumnType("double precision");

                            b1.HasKey("OperatorProgressId", "Id");

                            b1.ToTable("progresses");

                            b1.ToJson("Coordinates");

                            b1.WithOwner()
                                .HasForeignKey("OperatorProgressId");
                        });

                    b.Navigation("Coordinates");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("WebAppCellMapper.Data.Models.Station", b =>
                {
                    b.HasOne("WebAppCellMapper.Data.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });
#pragma warning restore 612, 618
        }
    }
}
